### PR TITLE
Restructure release notes chronology and custom TOC sidebar

### LINKED ISSUE #1440: Standardize copy-page widget placement across docs pages
### Describe the bug

Image

Image

### Steps to reproduce

Visit different pages on the doc

### Expected behavior

Standardize the placement, top-right.

### Link(s)

_No response_

### PR DESCRIPTION
**Pull request by Othryades**
## Summary

fix #1440, #1434

- Flatten the grouped "Beta v6.0" phased release into standalone versioned entries: v1.0, Beta v5.3, v5.2, v5.1, v5.0
- Rename "Assertions" → Beta v4.5, merge "Fusaka" into Beta v4.4
- Add custom scrollable release chronology TOC with sticky positioning and purple timeline (matching prod visual identity)
- Fix copy-page button alignment on release notes page (missing category label caused left-shift)
- Add legacy anchor targets (`#beta-v60`, `#forced-transactions`, `#small-fields`, `#eip-7702`, `#assertions`, `#fusaka`) for backward compatibility
- Update internal links in `deploy-subdomain.mdx` and `eip-7702.mdx` to point to new anchors
- Update stale "Beta v6.0" prose references to "Beta v5.0"

## Why

The old grouped "phased release" structure was confusing — each release should be a standalone, clearly versioned entry with its own date. The custom TOC makes the long release history navigable with bounded scroll. Anchor compatibility preserves external bookmarks.

## Test plan

- [x] Verify release notes page renders correctly (light + dark)
- [x] Verify TOC scrolls and highlights active section
- [x] Verify copy-page button is right-aligned
- [x] Verify legacy anchors resolve (`#beta-v60`, `#small-fields`, etc.)
- [x] Verify internal links from deploy-subdomain and eip-7702 pages
- [x] Check no regressions on standard docs pages

---

> [!NOTE]
> **Medium Risk**
> Introduces a new `release_toc` front-matter contract consumed by both MDX and a swizzled TOC component, so incorrect IDs or metadata can break release-note navigation and dates. CSS token changes also affect sticky layout offsets site-wide on desktop.
> 
> **Overview**
> Refactors `docs/changelog/release-notes.mdx` to use a new `release_toc` front-matter map as the single source of truth for release labels/dates, and updates entries (including new Beta v5.x sections, renamed Beta v4.5/Beta v4.4, and corrected EIP-7702 version references) to render dates via `<ChangelogDate sectionId=... />` while preserving backward-compatible deep links via `.legacy-anchor` IDs.
> 
> Adds a swizzled `src/theme/DocItem/TOC/Desktop` that renders a custom, scrollable “Release history” timeline TOC on the release-notes page (with per-release metadata text) while keeping the default TOC elsewhere; accompanying CSS introduces a desktop `--linea-sticky-header-offset` token, updates sidebar sticky calculations to use it, tweaks TOC hiding behavior, and fixes title-row right alignment. Related docs are updated to point at the new anchors and the forced-transactions page no longer links to a specific release section.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit f82467ecb5082fbfbf4bd270a2103a5598697a08. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: src/theme/DocItem/TOC/Desktop/index.js [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+  "beta-v51": { date: "Yield Boost - 30 Mar 2026" },
+  "beta-v50": { date: "EIP-7702 - 23 Mar 2026" },
+  "beta-v45": { date: "Assertions - 28 Jan 2026" },
+  "beta-v44": { date: "Fusaka - 3 Dec 2025" },
+  "beta-v43": { date: "17 Nov 2025" },
+  "beta-v42": { date: "5 Nov 2025" },
+  "beta-v41": { date: "30 Oct 2025" },
+  "beta-v40": { date: "22-28 Oct 2025" },
+  "beta-v311": { date: "6 Oct 2025" },
+  "beta-v31": { date: "Aug 2025 target" },
```
Comment (alainncls) [inline src/theme/DocItem/TOC/Desktop/index.js]: `RELEASE_TOC_META` duplicates chronology data outside the MDX source of truth, and it already drifted in this PR: `beta-v31` and `beta-v30` still say `target` here even though the release entries no longer do. That makes the custom TOC easy to desync from the page content over time.

File: docs/protocol/eip-7702.mdx [hunk 2]
```diff
@@ -10,7 +10,7 @@ image: /img/socialCards/eip-7702-support.jpg
 [**Prague hardfork**](https://eips.ethereum.org/EIPS/eip-7600) that allows a regular wallet
 (EOA—Externally Owned Account) to behave like a smart contract wallet without changing address,
 migrating funds, or creating a new seed phrase. The delegation persists until explicitly revoked.
-EIP-7702 is supported on Linea as of [Beta v6.0](../changelog/release-notes#beta-v60).
+EIP-7702 is supported on Linea as of [Beta v5.0](../changelog/release-notes#beta-v50).
```
Comment (alainncls) [inline docs/protocol/eip-7702.mdx:13]: This updates the activation timing here to Beta v5.0, but `docs/network/overview/ethereum-differences.mdx` still says EIP-7702 is available as of the Pectra upgrade (Beta v4). Could we align that page in the same PR so the docs don't ship contradictory timing?

File: docs/changelog/release-notes.mdx [hunk 3]
```diff
@@ -22,21 +22,32 @@ This page maintains a record and brief explanation of [Linea Security Council tr
 
 :::
 
-## Beta v6.0
+<a id="beta-v60" /><a id="forced-transactions" />
```
Comment (alainncls) [inline docs/changelog/release-notes.mdx]: These legacy anchors are plain empty `<a id>` markers, so old deep links like `#beta-v60` or `#forced-transactions` will resolve but won't inherit Docusaurus' sticky-header scroll margin. In practice the heading can land hidden under the fixed navbar. Could we keep the backward-compatible ids on elements that also get the anchor offset?

**Review by alainncls — APPROVED** [review]
